version: '3'

services:
  web:
    build: .
    ports:
      - "8087:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: julia2001
      MYSQL_DATABASE: biblioteca
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
